In [15]:
import tensorflow as tf

# Create a 2-dimensional tensor
x = tf.constant([[1, 2, 3], [4, 5, 6]])

print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [5]:
x + x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [6]:
y = tf.transpose(x)
print(y)
print(tf.matmul(x, y))

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[14 32]
 [32 77]], shape=(2, 2), dtype=int32)


In [7]:
x@tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [12]:
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [13]:
import tensorflow as tf

# Example input tensor
x = tf.constant([[1.0, 2.0, 3.0], [1.0, 2.0, 3.0]])  # Shape: (2, 3)

# Apply softmax along the last axis
softmax_result = tf.nn.softmax(x, axis=-1)

print("Input Tensor:")
print(x.numpy())

print("\nSoftmax Result:")
print(softmax_result.numpy())

Input Tensor:
[[1. 2. 3.]
 [1. 2. 3.]]

Softmax Result:
[[0.09003057 0.24472848 0.66524094]
 [0.09003057 0.24472848 0.66524094]]


In [17]:
x = tf.cast(x, dtype=tf.float32)
tf.nn.softmax(x, axis=-1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.66524094],
       [0.09003057, 0.24472848, 0.66524094]], dtype=float32)>

In [19]:
tf.reduce_sum(x, axis=-1, keepdims=True)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 6.],
       [15.]], dtype=float32)>

In [20]:
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>